import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SIZES } from '../../constants';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.black,
  },
  container: {
    width: '100%',
    aspectRatio: 16 / 13,
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 20,
    borderRadius: 0,
    backgroundColor: COLORS.black,
    overflow: 'hidden',
  },
  cloumn: {
    width: SIZES.width * 0.9,
    alignSelf: 'center',
    gap: SIZES.width * 0.025,
    marginTop: SIZES.height * 0.005,
  },
  title: {
    color: COLORS.white,
    fontSize: SIZES.w10 * 1.8,
    fontFamily: FONTS.Bold,
    textAlign: 'center',
    marginVertical: 5,
    letterSpacing: 0.5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SIZES.width * 0.0185,
  },
  text: {
    color: COLORS.white,
    fontFamily: FONTS.SemiBold,
    fontSize: SIZES.w2,
  },
  iconStyle: {
    width: SIZES.width * 0.03,
    height: SIZES.height * 0.03,
    resizeMode: 'contain',
  },
  buttonStyle: {
    height: SIZES.height * 0.064,
    marginBottom: SIZES.h5,
  },
  hdView: {
    backgroundColor: COLORS.gray200,
    paddingHorizontal: SIZES.width * 0.01,
    borderRadius: SIZES.width * 0.012,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hd: {
    color: COLORS.gray700,
    fontFamily: FONTS.Bold,
    fontSize: SIZES.w0,
    textAlign: 'center',
    marginTop: SIZES.height * 0.0025,
  },
  imdb: {
    width: SIZES.width * 0.075,
    height: SIZES.height * 0.02,
    borderRadius: SIZES.width * 0.008,
  },
  imdbText: {
    color: COLORS.white,
    fontFamily: FONTS.regular,
    fontSize: SIZES.w2,
  },
  dot: {
    color: COLORS.gray300,
    fontSize: SIZES.width * 0.032,
  },
  view: {
    width: SIZES.width * 0.89,
    alignSelf: 'center',
  },
  seprater: {
    height: SIZES.width * 0.0025,
    backgroundColor: COLORS.lightBlack,
    marginVertical: SIZES.height * 0.02,
  },
  heading: {
    color: COLORS.white,
    fontFamily: FONTS.Bold,
    fontSize: 18,
    marginBottom: 8,
  },
  subText: {
    color: COLORS.gray300,
    fontFamily: FONTS.medium,
    fontSize: SIZES.w2,
  },
  readMore: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: SIZES.w2,
    letterSpacing: 0.25,
  },
  iconBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
  },
  icons: {
    width: SIZES.width * 0.056,
    height: SIZES.height * 0.036,
    resizeMode: 'contain',
    marginBottom: 0,
  },
  iconText: {
    color: COLORS.gray400,
    fontFamily: FONTS.Medium,
    fontSize: 12,
    marginTop: 4,
  },
  topBottomView: {
    flexDirection: 'row',
    alignContent: 'center',
    marginTop: SIZES.height * 0.015,
    justifyContent: 'space-evenly',
    overflow: 'hidden',
  },
  topBottomText: {
    fontFamily: FONTS.Bold,
    fontSize: 13,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  PressableView: {
    marginVertical: SIZES.width * 0.015,
    paddingVertical: SIZES.width * 0.02,
    // width: '31%',
    alignItems: 'center',
    borderRadius: 100,
  },
  contentView: {
    marginTop: SIZES.width * 0.02,
    padding: 15,
    width: SIZES.width * 0.94,
    alignSelf: 'center',
    height: SIZES.width * 0.825,
    backgroundColor: COLORS.background,
    borderRadius: 16,
  },
  line: {
    height: SIZES.height * 0.0025,
    alignSelf: 'center',
    borderRadius: '30%',
    // marginLeft: SIZES.w12,
    backgroundColor: COLORS.primary,
  },
  line2: {
    height: SIZES.height * 0.0025,
    alignSelf: 'center',
    borderRadius: '30%',
    backgroundColor: COLORS.primary,
  },
  View: {
    marginTop: SIZES.height * 0.01,
    width: '100%',
    alignSelf: 'center',
  },

  flatListView: {
    height: SIZES.height * 0.3,
  },
  detailView: {
    backgroundColor: COLORS.lightBlack,
    paddingVertical: SIZES.height * 0.01,
    paddingHorizontal: SIZES.height * 0.02,
    width: SIZES.width,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SIZES.height * 0.005,
  },

  detailHeading: {
    color: COLORS.gray400,
    fontFamily: FONTS.regular,
    fontSize: SIZES.w5,
    width: SIZES.width * 0.24,
  },
  detailSubText: {
    color: COLORS.white,
    fontFamily: FONTS.regular,
    fontSize: SIZES.w5,
    flex: 1,
  },
  // Custom Video Player Styles
  fullscreenContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  fullScreenVideo: {
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
  },
  controlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
    padding: 10,
    zIndex: 10,
  },
  topControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  newTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
  },
  fullscreenTitle: {
    color: 'white',
    fontSize: 18,
    fontFamily: FONTS.Bold,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  rightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  centerControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 25,
    alignSelf: 'center',
    flex: 1,
  },
  bottomControls: {
    marginTop: 'auto',
  },
  controlButton: {
    padding: 10,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  timeText: {
    color: 'white',
    fontSize: 12,
    fontFamily: FONTS.SemiBold,
  },
  seekBarContainer: {
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 2,
    width: '100%',
    overflow: 'hidden',
  },
  seekBarProgress: {
    height: '100%',
    backgroundColor: COLORS.primary,
  },
  settingsButton: {
    position: 'absolute',
    top: 20,
    right: 60,
    zIndex: 11,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: SIZES.width * 0.5,
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    padding: 24,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  modalTitle: {
    color: 'white',
    fontSize: 20,
    fontFamily: FONTS.Bold,
    marginBottom: 20,
    textAlign: 'left',
  },
  modalItem: {
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  modalItemText: {
    color: COLORS.gray300,
    fontSize: 16,
    fontFamily: FONTS.medium,
  },
  modalItemActive: {
    color: COLORS.primary,
    fontFamily: FONTS.Bold,
  },
  sectionTitle: {
    color: COLORS.primary,
    fontSize: 14,
    fontFamily: FONTS.Bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 10,
    marginBottom: 10,
  },
  closeButton: {
    marginTop: 30,
    paddingVertical: 15,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 8,
    alignItems: 'center',
  },
  closeButtonText: {
    color: 'white',
    fontFamily: FONTS.Bold,
    fontSize: 16,
  },
  // Netflix-style Episode UI
  episodeItem: {
    flexDirection: 'row',
    width: SIZES.width * 0.94,
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  episodeThumbnail: {
    width: SIZES.width * 0.38,
    height: SIZES.width * 0.38 * (9 / 16), // Strict 16:9
    borderRadius: 8,
    backgroundColor: COLORS.gray800,
  },
  episodeThumbnailContainer: {
    position: 'relative',
  },
  playIconOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 8,
  },
  episodeInfo: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
  },
  episodeNum: {
    color: COLORS.primary,
    fontFamily: FONTS.Bold,
    fontSize: 11,
    marginBottom: 4,
    letterSpacing: 1,
  },
  episodeTitle: {
    color: COLORS.white,
    fontFamily: FONTS.Bold,
    fontSize: 15,
    marginBottom: 6,
  },
  episodeDescription: {
    color: COLORS.gray400,
    fontFamily: FONTS.Regular,
    fontSize: 12,
    lineHeight: 16,
  },
  // Season Dropdown
  seasonSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.lightBlack,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginLeft: SIZES.width * 0.03,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  seasonText: {
    color: COLORS.white,
    fontFamily: FONTS.Bold,
    fontSize: 14,
    marginRight: 8,
  },
  seasonDropdownIcon: {
    width: 12,
    height: 12,
    tintColor: COLORS.white,
    resizeMode: 'contain',
  },
  videoPlayer: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.black,
  },
  // Netflix-style Skip and Next Buttons
  nextEpisodeContainer: {
    position: 'absolute',
    bottom: 120,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  nextEpisodeText: {
    color: COLORS.black,
    fontFamily: FONTS.Bold,
    fontSize: 14,
    marginRight: 8,
  },
  skipButtonContainer: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  skipButtonText: {
    color: COLORS.black,
    fontFamily: FONTS.Bold,
    fontSize: 14,
  },
  // Network Error Modal Styles
  networkErrorContent: {
    width: SIZES.width * 0.8,
    backgroundColor: COLORS.lightBlack,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  networkErrorTitle: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.Bold,
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  networkErrorMsg: {
    color: COLORS.gray400,
    fontSize: 14,
    fontFamily: FONTS.Medium,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    marginBottom: 12,
  },
  retryButtonText: {
    color: COLORS.white,
    fontFamily: FONTS.Bold,
    fontSize: 16,
  },
  goBackButton: {
    paddingVertical: 12,
    width: '100%',
    alignItems: 'center',
  },
  // Vertical Side Indicators
  indicatorSideOverlay: {
    position: 'absolute',
    top: '20%',
    width: 50,
    height: '60%',
    backgroundColor: 'transparent',
    borderRadius: 25,
    zIndex: 1000,
    alignItems: 'center',
    justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: 'rgba(255,255,255,0.1)',
  },
  leftSide: {
    left: 30,
  },
  rightSide: {
    right: 30,
  },
  indicatorContainerSide: {
    flex: 1,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  indicatorTrackVertical: {
    width: 6,
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 3,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  indicatorFillVertical: {
    width: '100%',
    backgroundColor: '#FFB800',
    borderRadius: 3,
  },
});
